### PR TITLE
Continuous env

### PR DESCRIPTION
**Pull request by Rowing0914**
Hi,
I've read [your great entry](http://amid.fish/reproducing-deep-rl), and visited this repo!
Thank you for your post, I've literally learnt a lot from it!!

Regarding my RP, I just wanted to two things
- update this repo to be compatible with the latest gym because the previous implementation has got the warning saying `_step` function should be named as `step` (without underscore there).
- added the dot env which accepts the continuous action values.

Hope you'll like it and if you have time please check this RP and I'd like to know your thoughts on this change as well.

Best,

### CODE REVIEW

**Comment by mrahtz** [comment]
Hi! Sorry for the slow reply - it's been a crazy few weeks.

Thanks for your kind words for the post, and also for the pull request! This is a really nice feature addition.

I notice that the continuous version of the env is implemented in a separate class, resulting in the need to duplicate a lot of the code from the discrete class (e.g. in `__init__` and `step`). Could you refactor the code to remove this duplication? The cleanest way to do it is probably to create a parent class implementing the shared code, then subclass it for the discrete and continuous versions. Open to other suggestions, though.

**Comment by Rowing0914** [comment]
Hi @mrahtz ,

Thank you for your reivewing!!
I love your solution!! let me take time a bit and work on the modification following your advice!

Best,

**Comment by Rowing0914** [comment]
Hi, sorry, it seems like I need to fully focus on my current internship so that let me come back this pull request afte a couple of weeks...

**Comment by mrahtz** [comment]
Sure, no rush. Good luck with the internship!

**Comment by Rowing0914** [comment]
Hi @mrahtz 

I'm sorry for being late in responding. Finally, I could save some time to work on this and remove the redundancy by having the parent class for discrete/continuous action envs!
I think it's got cleaner than before!!

best,

**Comment by mrahtz** [comment]
Looks good. Thanks, and merry Christmas! :)

**Comment by Rowing0914** [comment]
Thank you for reviewing and merging!
Merry Christmas, too!!

**Pull request merged**
